### ISSUE TITLE
Example for HTML output

### ISSUE THREAD

**Issue by maxmeyer** [cucumber-attic/cucumber-pretty-formatter#3]
Someone [posted](https://github.com/cucumber/cucumber-html/issues/33#issuecomment-170786413) an example for an HTML report generated by [grunt-cucumberjs ](https://www.npmjs.com/package/grunt-cucumberjs) at [cucumber/cucumber-html](https://github.com/cucumber/cucumber-html). It looks good, but I'm sure if this is the direction where we are heading, but since this is kind of user input I posted it here.

**Comment by maxmeyer** [comment]
Personally I would not use 3D diagrams because the representation can be misleading: http://blog.visual.ly/2ds-company-3ds-a-crowd/.

**Comment by mattwynne** [comment]
I don't think this is relevant here. The pretty formatter is for the console. HTML output would be done by another tool in another repo.

**Comment by maxmeyer** [comment]
I think you're right, then we should change this line, shouldn't wee? https://github.com/cucumber/cucumber-pretty-formatter/blame/master/README.md#L9

**Comment by mattwynne** [comment]
yup
