### ISSUE TITLE
Add JS support

### ISSUE THREAD

**Issue by mucsi96** [cucumber-attic/cucumber-pretty-formatter#4]
It would be great to execute the formatter with Node.js using Cucumber.js output

**Comment by l3pp4rd** [comment]
hi, we are planning to make it as single binary executable for all OS platforms. I think it would be simple to run this executable with **stdin** event stream and pipe it to **stdout** output directly from the nodejs code. the requirement would be to have this binary in PATH

**Comment by mucsi96** [comment]
Ok. Thanks!
