### ISSUE TITLE
Pretty freezing up console unless redirected

### ISSUE THREAD

**Issue by jsbakker** [cucumber-attic/cucumber-pretty-formatter#8]
Firstly, I'm unsure if this is a problem with the formatter code itself or a problem with Calabash, which is the cucumber implementation I've been seeing the issue on. Either way, I have made them aware of it [in this post](https://github.com/calabash/calabash-android/issues/745) and have been going back and forth with them for months until I've reached a conclusion where the pretty formatter is an apparent point of failure.

Long story short, the terminal window eventually freezes up (and current processes are delayed) when running a series of tests. Exactly when and where it freezes is inconsistent, so it is not the tests themselves. The interesting part, is that it only happens when I am using the pretty formatter. And to reinforce that statement, the freeze also does not occur when I am redirecting pretty to a file, E.g. append `--format pretty > cal_dbg.txt 2>&1` to my cucumber command.

The freeze can be broken out of by pressing `Ctrl + C` and the tests will continue to execute normally. This tells me that perhaps some process which directs the STDOUT is being blocked somehow?

This has been encountered on Windows and I appear to have Cucumber 2.4.0 ruby gem installed as a dependency of my Calabash-Android installation, BTW

**Comment by l3pp4rd** [comment]
Hi, guess we need to rename this repository. This project is not yet used in any cucumber implementation. It is still an experiment to organize all formatters in a single language for all cucumber implementations. But for now, you should raise this issue in [cucumber ruby](https://github.com/cucumber/cucumber-ruby). Sorry for late answer.

**Comment by jsbakker** [comment]
Sorry for the troubles, and thanks for pointing me in the right direction.
